# Generated by Django 5.0.6 on 2024-08-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='Course/images/'),
        ),
    ]
