# Generated by Django 5.0.6 on 2024-11-06 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0004_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='enrolled_users',
        ),
    ]
