# Generated by Django 5.0.6 on 2024-11-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0005_remove_course_enrolled_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Course/images/'),
        ),
    ]
