# Generated by Django 5.0.6 on 2024-08-14 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_us', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
